removing multi-tenancy-gitops new cluster structure creation

diff --git a/ocaso/environments/cicd/new-roks-cluster-engine/tasks/new-roks-import-task.yaml b/ocaso/environments/cicd/new-roks-cluster-engine/tasks/new-roks-import-task.yaml
--- a/ocaso/environments/cicd/new-roks-cluster-engine/tasks/new-roks-import-task.yaml
+++ b/ocaso/environments/cicd/new-roks-cluster-engine/tasks/new-roks-import-task.yaml
@@ -108,41 +108,41 @@ spec:
         sleep 10
         oc apply -f import/secret.yaml
         set +x
-    - name: git-clone-multi-tenancy-gitops
-      image: $(params.git-image)
-      script: |
-        echo "********************"
-        echo "** Step git-clone **"
-        echo "********************"
-        echo
-        if [[ "$(params.debug)" == "True" ]]; then echo "DEBUG is enabled"; set -x; fi
-        mkdir -p /tmp/gitops
-        if [[ -n "${GIT_USERNAME}" ]] && [[ -n "${GIT_PRIV_TOKEN}" ]]; then
-            git clone "$(echo $(params.multi-tenancy-gitops-url) | awk -F '://' '{print $1}')://${GIT_USERNAME}:${GIT_PRIV_TOKEN}@$(echo $(params.multi-tenancy-gitops-url) | awk -F '://' '{print $2}')" /tmp/gitops
-        else
-            git clone $(params.multi-tenancy-gitops-url) /tmp/gitops
-        fi
-        cd /tmp/gitops
-        git checkout $(params.multi-tenancy-gitops-branch)
-        # Create new cluster structure
-        cd 0-bootstrap/spokeclusters/spoke-cluster-template
-        sh new-cluster.sh ${CLUSTER_NAME}
-        if [[ $? -ne 0 ]]
-        then 
-          echo "ERROR creating new cluster with new-cluster.sh"
-          exit 1
-        fi
-        cd /tmp/gitops
-        # Create new cluster definition
-        cd 0-bootstrap/hub/4-rhacm/argocd/clusters/imported
-        cp cluster-template.yaml_tmp ${CLUSTER_NAME}.yaml
-        sed -i'.bak' -e 's/CLUSTER_NAME/'"${CLUSTER_NAME}"'/g' ${CLUSTER_NAME}.yaml
-        rm ${CLUSTER_NAME}.yaml.bak
-        cd /tmp/gitops
-        # Commit changes
-        git config --global user.email "demo@example.com"
-        git config --global user.name "New ROKS cluster pipeline"
-        git add --all
-        git commit -m "NEW ROKS PIPELINE CHANGE - Cluster ${CLUSTER_NAME}"
-        git push origin $(params.multi-tenancy-gitops-branch)
-        set +x
+    # - name: git-clone-multi-tenancy-gitops
+    #   image: $(params.git-image)
+    #   script: |
+    #     echo "********************"
+    #     echo "** Step git-clone **"
+    #     echo "********************"
+    #     echo
+    #     if [[ "$(params.debug)" == "True" ]]; then echo "DEBUG is enabled"; set -x; fi
+    #     mkdir -p /tmp/gitops
+    #     if [[ -n "${GIT_USERNAME}" ]] && [[ -n "${GIT_PRIV_TOKEN}" ]]; then
+    #         git clone "$(echo $(params.multi-tenancy-gitops-url) | awk -F '://' '{print $1}')://${GIT_USERNAME}:${GIT_PRIV_TOKEN}@$(echo $(params.multi-tenancy-gitops-url) | awk -F '://' '{print $2}')" /tmp/gitops
+    #     else
+    #         git clone $(params.multi-tenancy-gitops-url) /tmp/gitops
+    #     fi
+    #     cd /tmp/gitops
+    #     git checkout $(params.multi-tenancy-gitops-branch)
+    #     # Create new cluster structure
+    #     cd 0-bootstrap/spokeclusters/spoke-cluster-template
+    #     sh new-cluster.sh ${CLUSTER_NAME}
+    #     if [[ $? -ne 0 ]]
+    #     then 
+    #       echo "ERROR creating new cluster with new-cluster.sh"
+    #       exit 1
+    #     fi
+    #     cd /tmp/gitops
+    #     # Create new cluster definition
+    #     cd 0-bootstrap/hub/4-rhacm/argocd/clusters/imported
+    #     cp cluster-template.yaml_tmp ${CLUSTER_NAME}.yaml
+    #     sed -i'.bak' -e 's/CLUSTER_NAME/'"${CLUSTER_NAME}"'/g' ${CLUSTER_NAME}.yaml
+    #     rm ${CLUSTER_NAME}.yaml.bak
+    #     cd /tmp/gitops
+    #     # Commit changes
+    #     git config --global user.email "demo@example.com"
+    #     git config --global user.name "New ROKS cluster pipeline"
+    #     git add --all
+    #     git commit -m "NEW ROKS PIPELINE CHANGE - Cluster ${CLUSTER_NAME}"
+    #     git push origin $(params.multi-tenancy-gitops-branch)
+    #     set +x
